import React from 'react'
import { Nav } from '../src/components/nav/Nav'
import { Footer } from '../src/components/Footer'
import '../src/styles/main.scss'
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta http-equiv="X-UA-Compatible" content="IE=edge" />

          <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png" />
          <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png" />
          <link rel="manifest" href="/images/site.webmanifest" />

          <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet" />
        </Head>
	<Nav />
	<Component {...pageProps} />
	<Footer />
	</>
}

export default MyApp
